name: build
on: [push, pull_request]
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            mariadb-version: 10.5
          - os: ubuntu-18.04
            mariadb-version: 10.5
          - os: ubuntu-18.04
            mariadb-version: 10.4
          - os: ubuntu-18.04
            mariadb-version: 10.3
          - os: ubuntu-18.04
            mariadb-version: 10.2
          - os: ubuntu-16.04
            mariadb-version: 10.5
          - os: ubuntu-16.04
            mariadb-version: 10.4
          - os: ubuntu-16.04
            mariadb-version: 10.3
          - os: ubuntu-16.04
            mariadb-version: 10.2
          - os: macos-10.15
            mariadb-version: 10.5
          - os: macos-10.15
            mariadb-version: 10.4
          - os: macos-10.15
            mariadb-version: 10.1
          - os: windows-2019
            mariadb-version: 10.5
          - os: windows-2019
            mariadb-version: 10.4
          - os: windows-2019
            mariadb-version: 10.3
          - os: windows-2019
            mariadb-version: 10.2
          - os: windows-2019
            mariadb-version: 10.1
    steps:
    - uses: ankane/setup-mariadb@v1
      with:
        mariadb-version: ${{ matrix.mariadb-version }}
    - run: mysql --version
    - run: mysqladmin create testdb
    - run: mysql -D testdb -e 'SELECT VERSION()'
